import { Picture } from './picture';

export const PICTURES: Picture[] = [
    new Picture('20160825_143849.jpg' ,'kitchen fitting at Winchester' ,'kitchen fitting at Winchester'),
    new Picture('20160825_143920.jpg' ,'kitchen fitting at Winchester' ,'kitchen fitting at Winchester'),
    new Picture('20160825_144024.jpg' ,'kitchen fitting at Winchester' ,'kitchen fitting at Winchester'),
    new Picture('20160707_110014.jpg' ),
    new Picture('20160519_090426.jpg' ,'kitchen fitting at Winchester' ,'kitchen fitting at Winchester'),
    new Picture('20160504_151752.jpg' ,'kitchen fitting at Eastleigh' ,'kitchen fitting at Eastleigh'),
    new Picture('20161109_141252.jpg' ),
    new Picture('20160816_121153.jpg' ,'kitchen fitting at Winchester' ,'kitchen fitting at Winchester'),
    new Picture('20160824_130307.jpg' ,'kitchen fitting at Winchester' ,'kitchen fitting at Winchester'),
    new Picture('k1.jpg' ,'kitchen fitting at Winchester' ,'kitchen fitting at Winchester'),
    new Picture('k2.jpg' ,'kitchen fitting at Winchester' ,'kitchen fitting at Winchester'),
    new Picture('k3.jpg' ,'kitchen fitting at Winchester' ,'kitchen fitting at Winchester'),
    new Picture('b1.jpg' ),
    new Picture('b2.jpg' ,'bathroom fitting at Southampton' ,'bathroom fitting at Southampton'),
    new Picture('b3.jpg' ,'bathroom tiling at Eastleigh' ,'bathroom tiling at Eastleigh'),
    new Picture('l1.jpg' ),
    new Picture('l2.jpg' ,'living room renovation at Southampton' ,'living room renovation at Southampton'),
    new Picture('l3.jpg' ,'living room renovation at Eastleigh' ,'living room renovation at Eastleigh'),
    new Picture('kitchenBefore.jpe' ,'kitchen before' ,'kitchen before'),
    new Picture('kitchenAfter.jpe' ,'kitchen fitting at Southampton' ,'kitchen fitting at Southampton'),
    new Picture('kitchenAfter2.jpe' ,'kitchen fitting at Eastleigh' ,'kitchen fitting at Eastleigh'),
    new Picture('bathroomBefore.jpe' ,'bathroom before' ,'bathroom before'),
    new Picture('bathroomAfter.jpe' ,'bathroom renovation at Eastleigh' ,'bathroom renovation at Eastleigh'),
    new Picture('bathroomAfter2.jpe' ,'bathroom renovation at Eastleigh' ,'bathroom renovation at Eastleigh'),
    new Picture('lazienka.jpg' ,'' ,''),
    new Picture('lazienka2.jpg' ,'bathroom renovation at Eastleigh' ,'bathroom renovation at Eastleigh'),
    new Picture('umywalka1.jpg' ,'bathroom renovation at Eastleigh' ,'bathroom renovation at Eastleigh'),
    new Picture('dom1.jpg' ,'' ,''),
    new Picture('dom2.jpg' ,'bathroom renovation at Eastleigh' ,'bathroom renovation at Eastleigh'),
    new Picture('dom3.jpg' ,'bathroom renovation at Eastleigh' ,'bathroom renovation at Eastleigh'),
    new Picture('kuchnia1.jpg' ,'' ,''),
    new Picture('kuchnia2.jpg' ,'house renovation at Eastleigh' ,'bathroom renovation at Eastleigh'),
    new Picture('deck1.jpg' ,'' ,''),
    new Picture('deck2.jpg' ,'house renovation at Eastleigh' ,'bathroom renovation at Eastleigh'),
    new Picture('houseBefore.jpe' ,'house before' ,'bathroom before'),
    new Picture('houseAfter.jpe' ,'house renovation at Eastleigh' ,'bathroom renovation at Eastleigh')
]