import { Picture } from './picture';

export const PICTURES: Picture[] = [
    new Picture('kitchen_eastleigh.jpg' ,'Kitchen fitting in Eastleigh' ,'Kitchen fitting in Eastleigh'),
    new Picture('kitchen_eastleigh_2.jpg' ,'Kitchen fitting in Eastleigh' ,'Kitchen fitting in Eastleigh'),
    new Picture('bath_eastleigh_1.jpg' ,'Bathroom instalation at Cranbury Rd, Eastleigh' ,'Bathroom instalation at Cranbury Rd, Eastleigh'),
    new Picture('painting_soton.jpg' ,'House painting and decorating in Southampton' ,'House painting and decorating in Southampton'),
    new Picture('gate_painting.jpg' ,'Gate restoration at Southampton' ,'Gate restoration at Southampton'),
    new Picture('bathroom_eastleigh.jpg' ,'Bathroom plumbing and tiling in Eastleigh' ,'Bathroom plumbing and tiling in Eastleigh'),
    new Picture('kitchen_eastleigh_1.jpg','Kitchen instalation at Cranbury Rd, Eastleigh','Kitchen instalation at Cranbury Rd, Eastleigh' ),
    new Picture('kitchen_ins.jpg' ,'Kitchen fitting in Southampton' ,'Kitchen fitting in Southampton'),
    new Picture('kitchen_ins_soton.jpg' ,'Kitchen fitting in Southampton' ,'Kitchen fitting in Southampton'),
    new Picture('k2.jpg' ,'Kitchen fitting at Nutbeem Rd, Eastleigh' ,'Kitchen fitting at Nutbeem Rd, Eastleigh'),
    new Picture('k3.jpg' ,'Kitchen fitting at Nutbeem Rd, Eastleigh' ,'Kitchen fitting at Nutbeem Rd, Eastleigh'),
    new Picture('b2.jpg' ,'Bathroom fitting at Nutbeem Rd, Eastleigh' ,'Bathroom fitting at Nutbeem Rd, Eastleigh'),
    new Picture('b3.jpg' ,'Bathroom fitting at Nutbeem Rd, Eastleigh' ,'Bathroom fitting at Nutbeem Rd, Eastleigh'),
    new Picture('l2.jpg' ,'Living room renovation at Nutbeem Rd, Eastleigh' ,'Living room renovation at Nutbeem Rd, Eastleigh'),
    new Picture('l3.jpg' ,'Living room renovation at Nutbeem Rd, Eastleigh' ,'Living room renovation at Nutbeem Rd, Eastleigh'),
    new Picture('kitchenAfter.jpe' ,'Kitchen fitting at High St, Eastleigh' ,'Kitchen fitting at High St, Eastleigh'),
    new Picture('kitchenAfter2.jpe' ,'Kitchen fitting at High St, Eastleigh' ,'Kitchen fitting at High St, Eastleigh'),
    new Picture('bathroomAfter.jpe' ,'Bathroom renovation at High St, Eastleigh' ,'Bathroom renovation at High St, Eastleigh'),
    new Picture('bathroomAfter2.jpe' ,'Bathroom renovation at High St, Eastleigh' ,'Bathroom renovation at High St, Eastleigh'),
    new Picture('lazienka2.jpg' ,'Bathroom renovation at Winchester' ,'Bathroom renovation at Winchester'),
    new Picture('umywalka1.jpg' ,'Bathroom renovation at Winchester' ,'Bathroom renovation at Winchester'),
    new Picture('dom2.jpg' ,'House painting in Southampton' ,'House painting in Southampton'),
    new Picture('dom3.jpg' ,'House painting in Southampton' ,'House painting in Southampton'),
    new Picture('kuchnia2.jpg' ,'Kitchen fitting at Desborough Rd, Eastleigh' ,'Kitchen fitting at Desborough Rd, Eastleigh'),
    new Picture('deck2.jpg' ,'Decking and fencing instalation in Southampton' ,'Decking and fencing instalation and painting in Southampton'),
    new Picture('houseAfter.jpe' ,'House painting at High St, Eastleigh' ,'House painting at High St, Eastleigh')
]